//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFIRST_MOVİES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int ActorID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> LanguageID { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
