//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFIRST_MOVİES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public int DirectorID { get; set; }
        public string DirectorName { get; set; }
        public Nullable<int> DirectorLanguageId { get; set; }
        public Nullable<int> FilmID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Language Language { get; set; }
    }
}
